import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

interface AuditEmailParams {
  to: string;
  websiteUrl: string;
  score: number;
  pagesCrawled: number;
  recommendations: number;
  resultsUrl: string;
  pdfUrl?: string;
}

export async function sendAuditReport(params: AuditEmailParams): Promise<boolean> {
  const { to, websiteUrl, score, pagesCrawled, recommendations, resultsUrl, pdfUrl } = params;

  const scoreColor = score >= 70 ? '#4aab6a' : score >= 40 ? '#d4952b' : '#e05555';
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'reports@whatseo.ai';

  try {
    await resend.emails.send({
      from: `WhatSEO.ai <${fromEmail}>`,
      to,
      subject: `Your SEO Audit is Ready — Score: ${score}/100`,
      html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background-color:#1a1a1a;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:40px 24px;">
    <!-- Header -->
    <div style="text-align:center;margin-bottom:32px;">
      <span style="font-size:20px;font-weight:bold;color:#f5f0e8;">What</span><span style="font-size:20px;font-weight:bold;color:#c9a85c;">SEO</span><span style="font-size:14px;color:#a09888;">.ai</span>
    </div>

    <!-- Score Card -->
    <div style="background-color:#232323;border-radius:16px;padding:32px;text-align:center;margin-bottom:24px;border:1px solid rgba(245,240,232,0.08);">
      <p style="color:#c9a85c;font-size:12px;text-transform:uppercase;letter-spacing:2px;margin:0 0 16px;">Audit Complete</p>
      <div style="font-size:64px;font-weight:bold;color:${scoreColor};margin:0;">${score}</div>
      <p style="color:#a09888;font-size:14px;margin:4px 0 0;">/ 100 SEO Health Score</p>
    </div>

    <!-- Stats -->
    <div style="display:flex;justify-content:center;gap:24px;margin-bottom:32px;text-align:center;">
      <div>
        <div style="font-size:24px;font-weight:bold;color:#c9a85c;">${pagesCrawled}</div>
        <div style="font-size:11px;color:#a09888;">Pages Analyzed</div>
      </div>
      <div>
        <div style="font-size:24px;font-weight:bold;color:#c9a85c;">${recommendations}</div>
        <div style="font-size:11px;color:#a09888;">Recommendations</div>
      </div>
    </div>

    <!-- Website -->
    <p style="color:#a09888;font-size:13px;text-align:center;margin-bottom:32px;">${websiteUrl}</p>

    <!-- CTA -->
    <div style="text-align:center;margin-bottom:24px;">
      <a href="${resultsUrl}" style="display:inline-block;background-color:#c9a85c;color:#1a1a1a;padding:14px 32px;border-radius:50px;text-decoration:none;font-weight:600;font-size:16px;">View Full Results</a>
    </div>

    ${pdfUrl ? `
    <div style="text-align:center;margin-bottom:32px;">
      <a href="${pdfUrl}" style="color:#c9a85c;font-size:13px;text-decoration:none;">Download PDF Report →</a>
    </div>
    ` : ''}

    <!-- Footer -->
    <div style="border-top:1px solid rgba(245,240,232,0.08);padding-top:24px;text-align:center;">
      <p style="color:#6b6358;font-size:11px;margin:0;">This report was generated by WhatSEO.ai</p>
      <p style="color:#6b6358;font-size:11px;margin:4px 0 0;">Questions? Reply to this email or contact hello@whatseo.ai</p>
    </div>
  </div>
</body>
</html>
      `.trim(),
    });
    return true;
  } catch (err) {
    console.error('Failed to send audit report email:', err);
    return false;
  }
}
