import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import type { FullAuditResult } from '../analyzer/types';

// Extend jsPDF with autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: Record<string, unknown>) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

const GOLD: [number, number, number] = [201, 168, 92];
const NAVY: [number, number, number] = [26, 26, 26];
const WHITE: [number, number, number] = [245, 240, 232];
const GRAY: [number, number, number] = [160, 152, 136];
const RED: [number, number, number] = [224, 85, 85];
const GREEN: [number, number, number] = [74, 171, 106];
const ORANGE: [number, number, number] = [212, 149, 43];

function getScoreColor(score: number): [number, number, number] {
  if (score >= 70) return GREEN;
  if (score >= 40) return ORANGE;
  return RED;
}

export function generateAuditPdf(result: FullAuditResult, websiteUrl: string): Buffer {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  function addPage() {
    doc.addPage();
    y = margin;
  }

  function checkPageBreak(needed: number) {
    if (y + needed > 270) addPage();
  }

  // --- COVER PAGE ---
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageWidth, 297, 'F');

  // Gold top bar
  doc.setFillColor(...GOLD);
  doc.rect(0, 0, pageWidth, 4, 'F');

  // Title
  doc.setTextColor(...GOLD);
  doc.setFontSize(12);
  doc.text('WhatSEO.ai', margin, 50);

  doc.setTextColor(...WHITE);
  doc.setFontSize(32);
  doc.text('SEO Audit Report', margin, 80);

  doc.setFontSize(16);
  doc.setTextColor(...GRAY);
  doc.text(websiteUrl, margin, 95);

  // Score circle (simple text representation)
  const scoreColor = getScoreColor(result.score.overall);
  doc.setFontSize(72);
  doc.setTextColor(...scoreColor);
  doc.text(String(result.score.overall), pageWidth / 2, 160, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(...GRAY);
  doc.text('/ 100  SEO Health Score', pageWidth / 2, 175, { align: 'center' });

  // Stats
  doc.setFontSize(11);
  doc.setTextColor(...WHITE);
  doc.text(`${result.pagesCrawled} pages analyzed  |  ${result.recommendations.length} recommendations  |  ${result.duration ? Math.round(result.duration / 1000) + 's' : ''}`, pageWidth / 2, 200, { align: 'center' });

  // Date
  doc.setFontSize(10);
  doc.setTextColor(...GRAY);
  doc.text(new Date(result.analyzedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), pageWidth / 2, 215, { align: 'center' });

  // Footer
  doc.setFontSize(8);
  doc.text('Generated by WhatSEO.ai  |  Confidential', pageWidth / 2, 280, { align: 'center' });

  // Gold bottom bar
  doc.setFillColor(...GOLD);
  doc.rect(0, 293, pageWidth, 4, 'F');

  // --- EXECUTIVE SUMMARY ---
  addPage();
  doc.setTextColor(...GOLD);
  doc.setFontSize(8);
  doc.text('01', margin, y);
  y += 5;
  doc.setTextColor(...NAVY);
  doc.setFontSize(20);
  doc.text('Executive Summary', margin, y);
  y += 3;
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + 30, y);
  y += 10;

  // Score breakdown table
  const catRows = Object.entries(result.score.categories).map(([key, val]) => {
    const labels: Record<string, string> = {
      technical: 'Technical SEO', content: 'Content Quality', onPage: 'On-Page SEO',
      schema: 'Schema Markup', performance: 'Performance', aiReadiness: 'AI Search Ready', images: 'Images',
    };
    return [labels[key] || key, `${val.score}/100`, `${val.weight}%`, val.weighted.toFixed(1)];
  });
  catRows.push(['Total', '', '', `${result.score.overall}/100`]);

  doc.autoTable({
    startY: y,
    head: [['Category', 'Score', 'Weight', 'Weighted']],
    body: catRows,
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [...NAVY], textColor: [...WHITE], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 243, 238] },
  });
  y = doc.lastAutoTable.finalY + 10;

  // Patterns summary
  checkPageBreak(60);
  doc.setTextColor(...NAVY);
  doc.setFontSize(14);
  doc.text('Patterns Detected', margin, y);
  y += 8;

  const patterns = [
    ['Thin Content Pages (<300 words)', String(result.thinContentPages?.length || 0)],
    ['Missing Title Tags', String(result.missingTitlePages?.length || 0)],
    ['Missing Meta Descriptions', String(result.missingMetaDescPages?.length || 0)],
    ['Missing Schema Markup', String(result.missingSchemaPages?.length || 0)],
    ['Duplicate Titles', String(result.duplicateTitles?.length || 0)],
    ['Slow Pages (>2s)', String(result.slowPages?.length || 0)],
    ['Broken Links', String(result.brokenLinks?.length || 0)],
  ];

  doc.autoTable({
    startY: y,
    head: [['Issue', 'Count']],
    body: patterns,
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [...NAVY], textColor: [...WHITE] },
    columnStyles: { 1: { halign: 'center', fontStyle: 'bold' } },
  });
  y = doc.lastAutoTable.finalY + 10;

  // --- RECOMMENDATIONS ---
  addPage();
  doc.setTextColor(...GOLD);
  doc.setFontSize(8);
  doc.text('02', margin, y);
  y += 5;
  doc.setTextColor(...NAVY);
  doc.setFontSize(20);
  doc.text('Prioritized Recommendations', margin, y);
  y += 3;
  doc.setDrawColor(...GOLD);
  doc.line(margin, y, margin + 30, y);
  y += 10;

  for (const rec of result.recommendations) {
    checkPageBreak(30);

    // Impact badge
    const impactColor = rec.impact === 'high' ? RED : rec.impact === 'medium' ? ORANGE : GREEN;
    doc.setFontSize(7);
    doc.setTextColor(...impactColor);
    doc.text(`${rec.impact.toUpperCase()} IMPACT  |  ${rec.effort.toUpperCase()} EFFORT`, margin, y);
    y += 5;

    doc.setFontSize(11);
    doc.setTextColor(...NAVY);
    doc.text(rec.title, margin, y);
    y += 5;

    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    const descLines = doc.splitTextToSize(rec.description, contentWidth);
    doc.text(descLines, margin, y);
    y += descLines.length * 4 + 2;

    if (rec.affectedUrls.length > 0) {
      doc.setFontSize(7);
      doc.setTextColor(...GOLD);
      doc.text(`${rec.affectedUrls.length} affected URLs`, margin, y);
      y += 3;
      doc.setTextColor(...GRAY);
      for (const url of rec.affectedUrls.slice(0, 5)) {
        doc.text(`  ${url}`, margin + 2, y);
        y += 3;
      }
      if (rec.affectedUrls.length > 5) {
        doc.text(`  ...and ${rec.affectedUrls.length - 5} more`, margin + 2, y);
        y += 3;
      }
    }

    y += 5;
  }

  // --- PAGES TABLE ---
  addPage();
  doc.setTextColor(...GOLD);
  doc.setFontSize(8);
  doc.text('03', margin, y);
  y += 5;
  doc.setTextColor(...NAVY);
  doc.setFontSize(20);
  doc.text('Pages Analyzed', margin, y);
  y += 3;
  doc.setDrawColor(...GOLD);
  doc.line(margin, y, margin + 30, y);
  y += 10;

  const pageRows = result.pages.slice(0, 50).map((p) => {
    const urlPath = p.url.replace(/^https?:\/\/[^/]+/, '') || '/';
    return [
      urlPath.length > 40 ? urlPath.substring(0, 40) + '...' : urlPath,
      String(p.statusCode),
      `${p.responseTime}ms`,
      String(p.content.wordCount),
      p.schema.jsonLdBlocks > 0 ? 'Yes' : 'No',
    ];
  });

  doc.autoTable({
    startY: y,
    head: [['URL', 'Status', 'Speed', 'Words', 'Schema']],
    body: pageRows,
    margin: { left: margin, right: margin },
    styles: { fontSize: 7, cellPadding: 2 },
    headStyles: { fillColor: [...NAVY], textColor: [...WHITE] },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { halign: 'center', cellWidth: 15 },
      2: { halign: 'center', cellWidth: 20 },
      3: { halign: 'center', cellWidth: 20 },
      4: { halign: 'center', cellWidth: 15 },
    },
  });

  // --- GOOGLE DATA (if available) ---
  if (result.googleData?.gsc || result.googleData?.ga4 || result.googleData?.crux) {
    addPage();
    doc.setTextColor(...GOLD);
    doc.setFontSize(8);
    doc.text('04', margin, y);
    y += 5;
    doc.setTextColor(...NAVY);
    doc.setFontSize(20);
    doc.text('Google Data', margin, y);
    y += 3;
    doc.setDrawColor(...GOLD);
    doc.line(margin, y, margin + 30, y);
    y += 10;

    if (result.googleData.gsc) {
      const gsc = result.googleData.gsc;
      doc.setFontSize(14);
      doc.setTextColor(...NAVY);
      doc.text('Search Console (90 days)', margin, y);
      y += 8;

      const queryRows = gsc.topQueries.slice(0, 20).map((q) => [
        q.query.length > 35 ? q.query.substring(0, 35) + '...' : q.query,
        String(q.clicks),
        String(q.impressions),
        (q.ctr * 100).toFixed(1) + '%',
        q.position.toFixed(1),
      ]);

      doc.autoTable({
        startY: y,
        head: [['Query', 'Clicks', 'Impressions', 'CTR', 'Position']],
        body: queryRows,
        margin: { left: margin, right: margin },
        styles: { fontSize: 7, cellPadding: 2 },
        headStyles: { fillColor: [...NAVY], textColor: [...WHITE] },
      });
      y = doc.lastAutoTable.finalY + 10;
    }

    if (result.googleData.ga4) {
      checkPageBreak(40);
      const ga4 = result.googleData.ga4;
      doc.setFontSize(14);
      doc.setTextColor(...NAVY);
      doc.text('Google Analytics (90 days)', margin, y);
      y += 8;

      doc.setFontSize(10);
      doc.setTextColor(...GRAY);
      doc.text(`Organic Sessions: ${ga4.organicSessions}  |  Organic Share: ${ga4.organicPercentage.toFixed(1)}%  |  Engagement: ${ga4.engagementRate.toFixed(1)}%`, margin, y);
      y += 10;
    }

    if (result.googleData.crux) {
      checkPageBreak(40);
      const crux = result.googleData.crux;
      doc.setFontSize(14);
      doc.setTextColor(...NAVY);
      doc.text('Core Web Vitals (Real Users)', margin, y);
      y += 8;

      const cwvRows = [
        crux.lcp ? ['LCP', `${crux.lcp.p75}ms`, `${crux.lcp.good}% good`, crux.lcp.p75 <= 2500 ? 'PASS' : 'FAIL'] : null,
        crux.inp ? ['INP', `${crux.inp.p75}ms`, `${crux.inp.good}% good`, crux.inp.p75 <= 200 ? 'PASS' : 'FAIL'] : null,
        crux.cls ? ['CLS', String(crux.cls.p75), `${crux.cls.good}% good`, crux.cls.p75 <= 0.1 ? 'PASS' : 'FAIL'] : null,
      ].filter(Boolean);

      if (cwvRows.length > 0) {
        doc.autoTable({
          startY: y,
          head: [['Metric', 'p75', 'Distribution', 'Status']],
          body: cwvRows,
          margin: { left: margin, right: margin },
          styles: { fontSize: 9, cellPadding: 3 },
          headStyles: { fillColor: [...NAVY], textColor: [...WHITE] },
        });
      }
    }
  }

  // --- FOOTER on every page ---
  const pageCount = doc.getNumberOfPages();
  for (let i = 2; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text('WhatSEO.ai  |  SEO Audit Report  |  Confidential', margin, 290);
    doc.text(`Page ${i - 1} of ${pageCount - 1}`, pageWidth - margin, 290, { align: 'right' });
    // Gold bottom line
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.3);
    doc.line(margin, 287, pageWidth - margin, 287);
  }

  return Buffer.from(doc.output('arraybuffer'));
}
