import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { FullAuditResult } from '../analyzer/types';

// Updated palette to match Academic Rebel design system
const PRIMARY: [number, number, number] = [145, 77, 0];      // #914d00
const DARK: [number, number, number] = [28, 28, 24];          // #1c1c18
const CREAM: [number, number, number] = [253, 249, 243];      // #fdf9f3
const SURFACE_LOW: [number, number, number] = [247, 243, 237]; // #f7f3ed
const MUTED: [number, number, number] = [74, 74, 68];         // #4a4a44
const LIGHT: [number, number, number] = [122, 122, 114];      // #7a7a72
const RED: [number, number, number] = [186, 26, 26];          // #ba1a1a
const GREEN: [number, number, number] = [77, 107, 50];        // #4d6b32
const ORANGE: [number, number, number] = [242, 140, 40];      // #f28c28
const OUTLINE: [number, number, number] = [219, 194, 176];    // #dbc2b0
const WHITE: [number, number, number] = [255, 255, 255];

function getScoreColor(score: number): [number, number, number] {
  if (score >= 70) return GREEN;
  if (score >= 40) return PRIMARY;
  return RED;
}

export function generateAuditPdf(result: FullAuditResult, websiteUrl: string): Buffer {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  function addPage() {
    doc.addPage();
    y = margin;
  }

  function checkPageBreak(needed: number) {
    if (y + needed > 270) addPage();
  }

  // --- COVER PAGE ---
  // Warm cream background
  doc.setFillColor(...CREAM);
  doc.rect(0, 0, pageWidth, 297, 'F');

  // Primary accent top bar
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, pageWidth, 4, 'F');

  // Brand
  doc.setTextColor(...PRIMARY);
  doc.setFontSize(12);
  doc.text('WhatSEO.ai', margin, 50);

  // Title
  doc.setTextColor(...DARK);
  doc.setFontSize(32);
  doc.text('SEO Audit Report', margin, 80);

  doc.setFontSize(16);
  doc.setTextColor(...MUTED);
  doc.text(websiteUrl, margin, 95);

  // Score
  const scoreColor = getScoreColor(result.score.overall);
  doc.setFontSize(72);
  doc.setTextColor(...scoreColor);
  doc.text(String(result.score.overall), pageWidth / 2, 160, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(...LIGHT);
  doc.text('/ 100  SEO Health Score', pageWidth / 2, 175, { align: 'center' });

  // Stats
  doc.setFontSize(11);
  doc.setTextColor(...DARK);
  doc.text(`${result.pagesCrawled} pages analyzed  |  ${result.recommendations.length} recommendations  |  ${result.duration ? Math.round(result.duration / 1000) + 's' : ''}`, pageWidth / 2, 200, { align: 'center' });

  // Date
  doc.setFontSize(10);
  doc.setTextColor(...LIGHT);
  doc.text(new Date(result.analyzedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), pageWidth / 2, 215, { align: 'center' });

  // Footer
  doc.setFontSize(8);
  doc.text('Generated by WhatSEO.ai  |  Confidential', pageWidth / 2, 280, { align: 'center' });

  // Bottom accent bar
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 293, pageWidth, 4, 'F');

  // Helper: render section heading with number
  function sectionHeading(num: string, title: string) {
    checkPageBreak(25);
    doc.setTextColor(...PRIMARY);
    doc.setFontSize(8);
    doc.text(num, margin, y);
    y += 8;
    doc.setTextColor(...DARK);
    doc.setFontSize(20);
    doc.text(title, margin, y);
    y += 3;
    doc.setDrawColor(...PRIMARY);
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + 30, y);
    y += 12;
  }

  // Helper: render multi-paragraph insight text
  function renderInsight(text: string, maxWidth: number) {
    if (!text) return;
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    const paragraphs = text.split('\n\n');
    for (const para of paragraphs) {
      const lines = doc.splitTextToSize(para.trim(), maxWidth);
      const blockHeight = lines.length * 4 + 3;
      checkPageBreak(blockHeight);
      doc.text(lines, margin, y);
      y += blockHeight;
    }
    y += 3;
  }

  const insights = result.insights;

  // --- EXECUTIVE SUMMARY ---
  addPage();
  sectionHeading('01', 'Executive Summary');

  // Top Priority callout — dynamic height
  if (insights?.topPriority) {
    doc.setFontSize(8);
    const prioLines = doc.splitTextToSize(insights.topPriority, contentWidth - 10);
    const boxHeight = prioLines.length * 4 + 14; // 14 = padding top (label + gap) + padding bottom

    checkPageBreak(boxHeight + 5);

    // Box background and border
    doc.setFillColor(250, 245, 235);
    doc.roundedRect(margin, y, contentWidth, boxHeight, 3, 3, 'F');
    doc.setDrawColor(...OUTLINE);
    doc.setLineWidth(0.3);
    doc.roundedRect(margin, y, contentWidth, boxHeight, 3, 3, 'S');

    // Label
    doc.setFontSize(7);
    doc.setTextColor(...PRIMARY);
    doc.text('#1 PRIORITY', margin + 5, y + 6);

    // Body text
    doc.setFontSize(8);
    doc.setTextColor(...DARK);
    doc.text(prioLines, margin + 5, y + 12);

    y += boxHeight + 8;
  }

  // Executive insight
  if (insights?.executive) {
    renderInsight(insights.executive, contentWidth);
  }

  // Score breakdown table
  checkPageBreak(50);
  const catRows = Object.entries(result.score.categories).map(([key, val]) => {
    const labels: Record<string, string> = {
      technical: 'Technical SEO', content: 'Content Quality', onPage: 'On-Page SEO',
      schema: 'Schema Markup', performance: 'Performance', aiReadiness: 'AI Search Ready', images: 'Images',
    };
    return [labels[key] || key, `${val.score}/100`, `${val.weight}%`, val.weighted.toFixed(1)];
  });
  catRows.push(['Total', '', '', `${result.score.overall}/100`]);

  autoTable(doc, {
    startY: y,
    head: [['Category', 'Score', 'Weight', 'Weighted']],
    body: catRows,
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 3, textColor: [...DARK] },
    headStyles: { fillColor: [...DARK], textColor: [...WHITE], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [...SURFACE_LOW] },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;

  // Patterns summary
  checkPageBreak(60);
  doc.setTextColor(...DARK);
  doc.setFontSize(14);
  doc.text('Patterns Detected', margin, y);
  y += 8;

  const patterns = [
    ['Thin Content Pages (<300 words)', String(result.thinContentPages?.length || 0)],
    ['Missing Title Tags', String(result.missingTitlePages?.length || 0)],
    ['Missing Meta Descriptions', String(result.missingMetaDescPages?.length || 0)],
    ['Missing Schema Markup', String(result.missingSchemaPages?.length || 0)],
    ['Duplicate Titles', String(result.duplicateTitles?.length || 0)],
    ['Slow Pages (>2s)', String(result.slowPages?.length || 0)],
    ['Broken Links', String(result.brokenLinks?.length || 0)],
  ];

  autoTable(doc, {
    startY: y,
    head: [['Issue', 'Count']],
    body: patterns,
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 3, textColor: [...DARK] },
    headStyles: { fillColor: [...DARK], textColor: [...WHITE] },
    alternateRowStyles: { fillColor: [...SURFACE_LOW] },
    columnStyles: { 1: { halign: 'center', fontStyle: 'bold' } },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;

  // --- EXPERT ANALYSIS ---
  addPage();
  sectionHeading('02', 'Expert Analysis');

  // Category-by-category expert insights
  if (insights) {
    const sections = [
      { key: 'technical', label: 'Technical SEO' },
      { key: 'onPage', label: 'On-Page SEO' },
      { key: 'content', label: 'Content Quality' },
      { key: 'schema', label: 'Structured Data' },
      { key: 'performance', label: 'Performance' },
      { key: 'aiReadiness', label: 'AI Search Readiness' },
      { key: 'images', label: 'Image Optimization' },
    ];

    for (const { key, label } of sections) {
      const text = insights[key as keyof typeof insights];
      if (!text) continue;
      checkPageBreak(25);
      doc.setFontSize(12);
      doc.setTextColor(...PRIMARY);
      doc.text(label, margin, y);
      y += 6;
      renderInsight(text, contentWidth);
      y += 2;
    }

    // Google data insights
    if (insights.googleData) {
      checkPageBreak(25);
      doc.setFontSize(12);
      doc.setTextColor(...PRIMARY);
      doc.text('Google Search & Analytics', margin, y);
      y += 6;
      renderInsight(insights.googleData, contentWidth);
    }
  }

  // --- RECOMMENDATIONS ---
  addPage();
  sectionHeading('03', 'Prioritized Recommendations');

  for (const rec of result.recommendations) {
    checkPageBreak(30);

    // Impact badge
    const impactColor = rec.impact === 'high' ? RED : rec.impact === 'medium' ? ORANGE : GREEN;
    doc.setFontSize(7);
    doc.setTextColor(...impactColor);
    doc.text(`${rec.impact.toUpperCase()} IMPACT  |  ${rec.effort.toUpperCase()} EFFORT`, margin, y);
    y += 5;

    doc.setFontSize(11);
    doc.setTextColor(...DARK);
    doc.text(rec.title, margin, y);
    y += 6;

    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    const descLines = doc.splitTextToSize(rec.description, contentWidth);
    checkPageBreak(descLines.length * 4 + 10);
    doc.text(descLines, margin, y);
    y += descLines.length * 4 + 2;

    if (rec.affectedUrls.length > 0) {
      doc.setFontSize(7);
      doc.setTextColor(...PRIMARY);
      doc.text(`${rec.affectedUrls.length} affected URLs`, margin, y);
      y += 4;
      doc.setTextColor(...LIGHT);
      for (const url of rec.affectedUrls.slice(0, 5)) {
        checkPageBreak(5);
        doc.text(`  ${url}`, margin + 2, y);
        y += 3.5;
      }
      if (rec.affectedUrls.length > 5) {
        doc.text(`  ...and ${rec.affectedUrls.length - 5} more`, margin + 2, y);
        y += 3.5;
      }
    }

    y += 6;
  }

  // --- PAGES TABLE ---
  addPage();
  sectionHeading('04', 'Pages Analyzed');

  const pageRows = result.pages.slice(0, 50).map((p) => {
    const urlPath = p.url.replace(/^https?:\/\/[^/]+/, '') || '/';
    return [
      urlPath.length > 40 ? urlPath.substring(0, 40) + '...' : urlPath,
      String(p.statusCode),
      `${p.responseTime}ms`,
      String(p.content.wordCount),
      p.schema.jsonLdBlocks > 0 ? 'Yes' : 'No',
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [['URL', 'Status', 'Speed', 'Words', 'Schema']],
    body: pageRows,
    margin: { left: margin, right: margin },
    styles: { fontSize: 7, cellPadding: 2, textColor: [...DARK] },
    headStyles: { fillColor: [...DARK], textColor: [...WHITE] },
    alternateRowStyles: { fillColor: [...SURFACE_LOW] },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { halign: 'center', cellWidth: 15 },
      2: { halign: 'center', cellWidth: 20 },
      3: { halign: 'center', cellWidth: 20 },
      4: { halign: 'center', cellWidth: 15 },
    },
  });

  // --- GOOGLE DATA (if available) ---
  if (result.googleData?.gsc || result.googleData?.ga4 || result.googleData?.crux) {
    addPage();
    sectionHeading('05', 'Google Data');

    if (result.googleData.gsc) {
      const gsc = result.googleData.gsc;
      doc.setFontSize(12);
      doc.setTextColor(...PRIMARY);
      doc.text('Search Console (90 days)', margin, y);
      y += 8;

      const queryRows = gsc.topQueries.slice(0, 20).map((q) => [
        q.query.length > 35 ? q.query.substring(0, 35) + '...' : q.query,
        String(q.clicks),
        String(q.impressions),
        (q.ctr * 100).toFixed(1) + '%',
        q.position.toFixed(1),
      ]);

      autoTable(doc, {
        startY: y,
        head: [['Query', 'Clicks', 'Impressions', 'CTR', 'Position']],
        body: queryRows,
        margin: { left: margin, right: margin },
        styles: { fontSize: 7, cellPadding: 2, textColor: [...DARK] },
        headStyles: { fillColor: [...DARK], textColor: [...WHITE] },
        alternateRowStyles: { fillColor: [...SURFACE_LOW] },
      });
      y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
    }

    if (result.googleData.ga4) {
      checkPageBreak(40);
      const ga4 = result.googleData.ga4;
      doc.setFontSize(12);
      doc.setTextColor(...PRIMARY);
      doc.text('Google Analytics (90 days)', margin, y);
      y += 8;

      doc.setFontSize(10);
      doc.setTextColor(...MUTED);
      doc.text(`Organic Sessions: ${ga4.organicSessions}  |  Organic Share: ${ga4.organicPercentage.toFixed(1)}%  |  Engagement: ${ga4.engagementRate.toFixed(1)}%`, margin, y);
      y += 10;
    }

    if (result.googleData.crux) {
      checkPageBreak(40);
      const crux = result.googleData.crux;
      doc.setFontSize(12);
      doc.setTextColor(...PRIMARY);
      doc.text('Core Web Vitals (Real Users)', margin, y);
      y += 8;

      const cwvRows: string[][] = [];
      if (crux.lcp) cwvRows.push(['LCP', `${crux.lcp.p75}ms`, `${crux.lcp.good}% good`, crux.lcp.p75 <= 2500 ? 'PASS' : 'FAIL']);
      if (crux.inp) cwvRows.push(['INP', `${crux.inp.p75}ms`, `${crux.inp.good}% good`, crux.inp.p75 <= 200 ? 'PASS' : 'FAIL']);
      if (crux.cls) cwvRows.push(['CLS', String(crux.cls.p75), `${crux.cls.good}% good`, crux.cls.p75 <= 0.1 ? 'PASS' : 'FAIL']);

      if (cwvRows.length > 0) {
        autoTable(doc, {
          startY: y,
          head: [['Metric', 'p75', 'Distribution', 'Status']],
          body: cwvRows,
          margin: { left: margin, right: margin },
          styles: { fontSize: 9, cellPadding: 3, textColor: [...DARK] },
          headStyles: { fillColor: [...DARK], textColor: [...WHITE] },
          alternateRowStyles: { fillColor: [...SURFACE_LOW] },
        });
      }
    }
  }

  // --- FOOTER on every page ---
  const pageCount = doc.getNumberOfPages();
  for (let i = 2; i <= pageCount; i++) {
    doc.setPage(i);
    // Cream page background
    doc.setFillColor(...CREAM);
    doc.rect(0, 0, pageWidth, 297, 'F');
    // Re-draw content by... we can't retroactively set bg. Skip bg for inner pages.
  }

  // Actually — jsPDF renders in order, so background must be set before content.
  // Instead, just add footer elements on top.
  for (let i = 2; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(...LIGHT);
    doc.text('WhatSEO.ai  |  SEO Audit Report  |  Confidential', margin, 290);
    doc.text(`Page ${i - 1} of ${pageCount - 1}`, pageWidth - margin, 290, { align: 'right' });
    // Accent bottom line
    doc.setDrawColor(...PRIMARY);
    doc.setLineWidth(0.3);
    doc.line(margin, 287, pageWidth - margin, 287);
  }

  return Buffer.from(doc.output('arraybuffer'));
}
